### ISSUE TITLE
Why added two container?

### ISSUE THREAD

**Issue by prasanth-j** [santhanakumar-p/html#13]
https://github.com/santhanakumar-p/html/blob/5e04298a90c6b412227832b4aa24e00fe39ca14e/edit.html#L15C33-L15C33

**Comment by santhanakumar-p** [comment]
Now remove the container.

**Comment by santhanakumar-p** [comment]
Now we have clear the container.

**Comment by santhanakumar-p** [comment]
Now we have clear the container.
